---
region: 'eu-west-2'

component: 'test'

work_directory: 'build'
configuration_directory: "%{hiera('work_directory')}/%{hiera('source_directory')}"

domain_name: "greasedscone.uk"
subdomain: "api.%{hiera('deployment_identifier')}"
public_zone_id: "Z4Q2X3ESOZT4N"
