---
source_directory: "spec/infra/harness"
state_file: "%{hiera('project_directory')}/state/harness.tfstate"
vars:
  region: "%{hiera('region')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  domain_name: "%{hiera('domain_name')}"
  subdomain: "%{hiera('subdomain')}"
  public_zone_id: "%{hiera('public_zone_id')}"

  create_custom_domain: 'no'

